local __red = "\27[31;1m"
local __midblue = "\27[91;1m"
local __green = "\27[32;1m"
local __lightgreen = "\27[92;1m"
local __darkgreen = "\27[32;1m"
local __cyan = "\27[96;1m"
local __darkcyan = "\27[36;1m"
local __reset = "\27[0m"
local __white = "\27[37;m"
local __darkred = "\27[31;m"
local __yellow = "\27[93;1m"
local __choices = {
	["red"] = __red,
	["midblue"] = __midblue,
	["green"] = __green,
	["lightgreen"] = __lightgreen,
	["darkgreen"] = __darkgreen,
	["cyan"] = __cyan,
	["darkcyan"] = __darkcyan,
	["white"] = __white,
	["darkred"] = __darkred,
	["yellow"] = __yellow
}
